server:
  port: 6001
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: admin
          uri: lb://lead-news-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix= 1
        - id: user
          uri: lb://lead-news-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
